FROM python

WORKDIR /app

COPY . /app

CMD ["python", "rng.py"]


rng.py
from random import randint

min_number = int(input("Please enter the min number: ))
max_number = int(input("Please enter the max number: ))

if (max_number < min_number):
    print("Invalid input - shutting down...")
else:
    rnd_number = randint(min_number, max_number)
    print(rnd_number)


#Video 33

docker run -it "image"    #run the container with interactive